apiVersion: v1
kind: Pod
metadata: 
   name: myapp-pod
   namespace: pod
   labels:
      app: myapp
      type: front-end
   annotations:
      buildversion: 1.34


spec:
  containers:
     - name: nginx-container
       image: nginx
       ports:
          - containerPort: 8080
       env:
       - name: APP_COLOR
         value: pink