apiVersion: v1
kind: Pod
metadata:
   name: myapp
   namespace: pod
   labels:
     app: myapp
     type: front-end
   annotations:
     buildversion: 1.18

spec:
   containers:
     - name: nginx-container
       image: nginx
   nodeSelector:
       siza: Large  